version: '24.3'

services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    image: hotel:django
    container_name: app_container
    command: gunicorn hotel.wsgi:application --bind 0.0.0.0:8000