# Generated by Django 5.0.2 on 2024-05-24 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0002_informe_delete_tipo_remove_habitacion_numero_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='cliente_id',
        ),
        migrations.AddField(
            model_name='reserva',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sistema.cliente'),
            preserve_default=False,
        ),
    ]
